INSERT INTO polls (
  creator_email,
  question,
  answer_1,
  description_1,
  answer_2,
  description_2,
  answer_3,
  description_3,
  answer_4,
  description_4,
  name_required,
  result_url,
  submission_url
) VALUES (
  'fakeemail@gmail.com',
  'What is your favourite colour?',
  'red',
  'dfhdsfnsdovindsaovnosadivnsdva',
  'blue',
  'jhdsiufhweuewuilnaweicubwciuwe',
  'green',
  'fjdshfkuasdhfuiasfhas',
  'pink',
  'kdjfhldsufhdshjakjfhasldkjf',
  'true',
  'f3rkaklkk3',
  'votesaklkk3'
), (
  'anotherfakeemail@gmail.com',
  'What is your favourite meal?',
  'Tacos',
  'delicious',
  'Spaghetti',
  'italian',
  'Curry',
  'Spicy',
  'Poutine',
  'canadian',
  'false',
  'kassladksjd3',
  'votesaklkk3'
);
