INSERT INTO polls (
  creator_email,
  result_url,
  submission_url,
  question,
  answer_1,
  description_1,
  answer_2,
  description_2,
  answer_3,
  description_3,
  answer_4,
  description_4,
  name_required
) VALUES (
  'fakeemail@gmail.com',
  '/eiruoewiru',
  '/jbdivbdsiu',
  'What is your favourite colour?',
  'red',
  'dfhdsfnsdovindsaovnosadivnsdva',
  'blue',
  'jhdsiufhweuewuilnaweicubwciuwe',
  'green',
  'fjdshfkuasdhfuiasfhas',
  'pink',
  'kdjfhldsufhdshjakjfhasldkjf',
  'true'
), (
  'anotherfakeemail@gmail.com',
  '/dsakjdhsakjd',
  '/fhdsufhsdkjf',
  'What is your favourite meal?',
  'Tacos',
  'delicious',
  'Spaghetti',
  'italian',
  'Curry',
  'Spicy',
  'Poutine',
  'canadian',
  'false'
);
